### ISSUE TITLE
Change `master` to `main`

### ISSUE THREAD

**Issue by evaporei** [edn-rs/edn-derive#34]
I don't have permission, only @naomijub has.

Related https://github.com/edn-rs/edn-rs/issues/128#issuecomment-1861771825

**Comment by naomijub** [comment]
😱 will try to do it today before going out for vacation.

@evaporei @Grinkers i will probably be a bit offline until February due to my vacation.

**Comment by Grinkers** [comment]
> 😱 will try to do it today before going out for vacation.
> 
> @evaporei @Grinkers i will probably be a bit offline until February due to my vacation.

@naomijub  Have a nice vacation!

I think progress with this crate will halt until then, due to the circular dependency with `edn-rs` and needing releases (guessing no time to setup publishing keys on the new org).

Also with `edn-rs`, a lot of PRs are piling up. I actually have time over the holidays, so I was going to try and get both close to 1.0 release candidates. Due to the conflicts, I just can't keep things clean in separate PRs with separate issues. Eg. the fix numbers to parse single digit numbers like `"7"` conflicted with `no_std`, error reworking, etc.

@evaporei do you want to track/review things on the edn-rs org and just have both `edn-rs` and `edn-derive` use git to reference each other (no releases), or should I just work on my own fork and have a mega huge PR for 1.0 candidate in Feb?

**Comment by Grinkers** [comment]
@naomijub realized my last message could read poorly. Truly, have a nice vacation!

I'm doing all this mostly for fun. I'm already using edn-rs with `edn-rs = { git = "https://github.com/Grinkers/edn-rs.git", default-features = false }` so I don't mind at all!

**Comment by naomijub** [comment]
@Grinkers  if you send me your crates profile I can add you to allow you to publish

**Comment by Grinkers** [comment]
> @Grinkers if you send me your crates profile I can add you to allow you to publish

I don't have one. What's the recommended way to link? Github? I'm looking at it, but what would probably be ideal is to create one for the org itself.
